# core/context_manager.py
"""
Context managers for safe browser session management.

Supports two authentication modes:
  1. Persistent profile (user_data_dir) — for local dev with saved Chrome profile.
  2. State-based (storage_state)        — for Docker/Cloud Run using state.json or
                                           PW_STATE_B64 env var generated by
                                           scripts/crear_sesion.py.

Integration with scraping:
    from src.core.context_manager import mycase_session, mycase_session_state
    from src.scraping import download_pdfs, extract_case_notes, send_text_message

    # With cookie state (recommended for Cloud Run):
    with mycase_session_state() as page:
        notes  = extract_case_notes(page, entity_id)
"""
import base64
import json
import tempfile
import threading
from contextlib import contextmanager
from typing import Generator, Optional, Tuple

from playwright.sync_api import sync_playwright, Page, BrowserContext, Playwright, Browser
from playwright.sync_api import TimeoutError as PlaywrightTimeout

from src.core import config
from src.core.exceptions import AuthenticationError, SessionExpiredError
from src.utils.logger import get_logger

logger = get_logger(__name__)

# Limits to 3 simultaneous browsers per container instance to save RAM on Cloud Run
browser_semaphore = threading.Semaphore(3)

# URL tokens that indicate the session is on a login page (not authenticated)
_LOGIN_TOKENS = ("login", "sign_in", "sign-in", "auth.mycase.com")


# ---------------------------------------------------------------------------
# State helpers (shared by scripts and context managers)
# ---------------------------------------------------------------------------

def load_state_path() -> Optional[str]:
    """
    Resolve Playwright session-state path.
    Priority:
        1. PW_STATE_B64 env var (base64-encoded state.json) → decoded to a temp file.
        2. STATE_FILE config path (local state.json file).
    """
    raw = config.PW_STATE_B64
    if raw:
        try:
            decoded = base64.b64decode(raw)
            json.loads(decoded)  # validate JSON before writing
            tmp = tempfile.NamedTemporaryFile(
                suffix=".json", delete=False, mode="wb", prefix="pw_state_"
            )
            tmp.write(decoded)
            tmp.close()
            logger.info("Session state loaded from PW_STATE_B64 (%d bytes)", len(decoded))
            return tmp.name
        except Exception as e:
            logger.warning("PW_STATE_B64 is set but invalid: %s", e)

    if config.STATE_FILE.exists():
        logger.info("Session state loaded from %s", config.STATE_FILE)
        return str(config.STATE_FILE)

    return None


def check_session_active(page: Page) -> bool:
    """Return True if *page* is on an active (authenticated) MyCase page."""
    try:
        page.wait_for_load_state("networkidle", timeout=10_000)
    except Exception:
        pass
    url = page.url
    return "mycase.com" in url and not any(t in url for t in _LOGIN_TOKENS)


# ---------------------------------------------------------------------------
# Internal context builders
# ---------------------------------------------------------------------------

def _build_browser_args(headless: bool) -> list[str]:
    """Optimized browser arguments for Cloud Run (low memory)."""
    args = [
        "--no-sandbox",
        "--disable-dev-shm-usage",  # Crucial for Cloud Run
        "--single-process",        # Reduces RAM consumption
        "--disable-gpu",
        "--disable-extensions",
        "--disable-blink-features=AutomationControlled",
        "--start-maximized",
        "--password-store=basic",
        "--use-mock-keychain",
    ]
    if headless:
        args.append("--headless=new")
    return args


def _apply_resource_blocking(page: Page) -> None:
    """Block resource types listed in config.PW_BLOCK_RESOURCES for speed."""
    if config.PW_BLOCK_RESOURCES:
        page.route(
            "**/*",
            lambda route, req: (
                route.abort()
                if req.resource_type in config.PW_BLOCK_RESOURCES
                else route.continue_()
            ),
        )


def _create_persistent_context(headless: bool = True):
    """Launch a persistent Playwright context."""
    p = sync_playwright().start()
    try:
        launch_kwargs = {
            "user_data_dir": str(config.PW_USER_DATA_DIR),
            "headless": False,  # controlled via args
            "args": _build_browser_args(headless),
            "viewport": {"width": 1920, "height": 1080},
        }
        if config.PW_BROWSER_CHANNEL:
            launch_kwargs["channel"] = config.PW_BROWSER_CHANNEL

        logger.info("Launching persistent context | headless=%s", headless)
        context = p.chromium.launch_persistent_context(**launch_kwargs)
        page = context.pages[0]
        page.set_default_timeout(config.PW_TIMEOUT_MS)
        _apply_resource_blocking(page)
        return p, context, page
    except Exception:
        logger.exception("Error creating persistent context")
        try:
            p.stop()
        except Exception:
            pass
        raise


def _create_state_context(state_path: str) -> Tuple[Playwright, Browser, BrowserContext, Page]:
    """Launch an ephemeral context with storage state."""
    p = sync_playwright().start()
    try:
        launch_kwargs: dict = {
            "headless": False,  # controlled via args
            "args": _build_browser_args(config.PW_HEADLESS),
        }
        if config.PW_BROWSER_CHANNEL:
            launch_kwargs["channel"] = config.PW_BROWSER_CHANNEL

        logger.info("Launching state context | state=%s", state_path)
        browser = p.chromium.launch(**launch_kwargs)
        context = browser.new_context(
            storage_state=state_path,
            viewport={"width": 1920, "height": 1080},
        )
        page = context.new_page()
        page.set_default_timeout(config.PW_TIMEOUT_MS)
        _apply_resource_blocking(page)
        return p, browser, context, page
    except Exception:
        logger.exception("Error creating state context")
        try:
            p.stop()
        except Exception:
            pass
        raise


# ---------------------------------------------------------------------------
# Public context managers
# ---------------------------------------------------------------------------

@contextmanager
def mycase_session(auto_login: bool = True) -> Generator[Page, None, None]:
    """Sync context manager for persistent browser session."""
    p = context = page = None
    with browser_semaphore:
        try:
            p, context, page = _create_persistent_context(headless=config.PW_HEADLESS)
            if auto_login:
                _ensure_logged_in(page)
            yield page
        finally:
            if context: context.close()
            if p: p.stop()


@contextmanager
def mycase_session_state() -> Generator[Page, None, None]:
    """Sync context manager for state-based (cookie) browser session."""
    state_path = load_state_path()
    if not state_path:
        raise AuthenticationError("No session state found (PW_STATE_B64 or state.json)")

    p = browser = context = page = None
    with browser_semaphore:
        try:
            p, browser, context, page = _create_state_context(state_path)
            
            # Verify session
            page.goto(config.MYCASE_BASE_URL, wait_until="domcontentloaded", timeout=config.PW_TIMEOUT_MS)
            if not check_session_active(page):
                raise SessionExpiredError("Session state is expired or invalid.")

            yield page
        finally:
            if context: context.close()
            if browser: browser.close()
            if p: p.stop()


def _ensure_logged_in(page: Page) -> None:
    """Manual login logic for persistent-profile mode."""
    try:
        page.goto(config.DASHBOARD_URL, wait_until="domcontentloaded", timeout=60_000)
        
        # Check if already logged in (navbar visible)
        if page.is_visible("nav") or page.is_visible("text=Home"):
            logger.info("Active session detected")
            return

        logger.info("No active session — attempting login...")
        if not config.MYCASE_EMAIL or not config.MYCASE_PASSWORD:
            raise AuthenticationError("MYCASE_EMAIL and MYCASE_PASSWORD must be configured")

        page.fill("#login_session_email", config.MYCASE_EMAIL)
        page.fill("#login_session_password", config.MYCASE_PASSWORD)
        
        with page.expect_navigation(timeout=30_000):
            page.click("#login-form-submit")
        
        if not check_session_active(page):
            raise AuthenticationError("Login failed - dashboard not reached.")
            
        logger.info("Login successful")
    except Exception as e:
        logger.error("Login process failed: %s", e)
        raise AuthenticationError(f"Login failed: {e}")



@contextmanager
def mycase_session_full(auto_login: bool = True) -> Generator[Tuple[Playwright, BrowserContext, Page], None, None]:
    """
    Context manager — yields full Playwright objects (persistent-profile mode).
    Use when you need direct access to the context or playwright instance.
    """
    p = context = page = None
    with browser_semaphore:
        try:
            p, context, page = _create_persistent_context(headless=config.PW_HEADLESS)
            if auto_login:
                _ensure_logged_in(page)
            yield p, context, page
        finally:
            if context:
                try: context.close()
                except: pass
            if p:
                try: p.stop()
                except: pass


@contextmanager
def mycase_auto_session() -> Generator[Page, None, None]:
    """
    Unified context manager that automatically chooses the best session:
    1. If PW_STATE_B64 or state.json exists, uses state-based session.
    2. Otherwise, uses persistent profile session with auto-login.
    """
    state_path = load_state_path()
    if state_path:
        logger.info("Using state-based (cookies) session for this task.")
        with mycase_session_state() as page:
            yield page
    else:
        logger.info("Using persistent profile (folder) session for this task.")
        with mycase_session() as page:
            yield page
